"""
AlgoVision AI — Deterministic Visualization Resolver
Replaces the AI-based Visualization Planner with a zero-cost lookup table.
No API call needed — maps algorithmType → visualization config deterministically.
"""


# ── Default config (used when algorithmType is not recognized) ──
_DEFAULT_VIZ = {
    "visualizationType": "2d-array",
    "renderMode": "2d",
    "layout": "horizontal",
    "animationStyle": "highlight",
    "colorScheme": "comparison",
    "elementShape": "bar",
    "showPointers": False,
    "showCallStack": False,
    "showDPTable": False,
    "showMatrix": False,
    "reasoning": "Default 2D array visualization",
}

# ── Lookup table: algorithmType → visualization config ──
VIZ_CONFIG_MAP = {
    "sorting": {
        "visualizationType": "2d-bars",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "swap",
        "colorScheme": "comparison",
        "elementShape": "bar",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Bar chart visualization for comparing and swapping array elements",
    },
    "searching": {
        "visualizationType": "2d-array",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "highlight",
        "colorScheme": "comparison",
        "elementShape": "bar",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Array visualization with pointer-based search window highlighting",
    },
    "graph-traversal": {
        "visualizationType": "3d-graph",
        "renderMode": "3d",
        "layout": "force-directed",
        "animationStyle": "traverse",
        "colorScheme": "status",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Graph node visualization for BFS/DFS traversal",
    },
    "tree": {
        "visualizationType": "3d-tree",
        "renderMode": "3d",
        "layout": "hierarchical",
        "animationStyle": "traverse",
        "colorScheme": "status",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Hierarchical tree visualization for tree algorithms",
    },
    "dynamic-programming": {
        "visualizationType": "2d-grid",
        "renderMode": "2d",
        "layout": "grid",
        "animationStyle": "fill",
        "colorScheme": "heatmap",
        "elementShape": "rectangle",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": True,
        "showMatrix": False,
        "reasoning": "Grid/table visualization for DP state transitions",
    },
    "recursion": {
        "visualizationType": "3d-stack",
        "renderMode": "3d",
        "layout": "vertical",
        "animationStyle": "grow",
        "colorScheme": "categorical",
        "elementShape": "card",
        "showPointers": False,
        "showCallStack": True,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Call stack visualization for recursive function calls",
    },
    "greedy": {
        "visualizationType": "2d-array",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "highlight",
        "colorScheme": "gradient",
        "elementShape": "bar",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Array visualization highlighting greedy selection choices",
    },
    "sliding-window": {
        "visualizationType": "2d-pointers",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "slide",
        "colorScheme": "comparison",
        "elementShape": "rectangle",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Array with sliding window pointers visualization",
    },
    "two-pointers": {
        "visualizationType": "2d-pointers",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "slide",
        "colorScheme": "comparison",
        "elementShape": "rectangle",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Array visualization with two converging/diverging pointers",
    },
    "backtracking": {
        "visualizationType": "3d-tree",
        "renderMode": "3d",
        "layout": "hierarchical",
        "animationStyle": "traverse",
        "colorScheme": "status",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": True,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Decision tree visualization for backtracking exploration",
    },
    "hashing": {
        "visualizationType": "2d-table",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "highlight",
        "colorScheme": "comparison",
        "elementShape": "rectangle",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Hash table visualization for key-value lookups",
    },
    "hash-map": {
        "visualizationType": "2d-bars",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "highlight",
        "colorScheme": "comparison",
        "elementShape": "bar",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Array + hash map visualization for lookup-based algorithms",
    },
    "stack": {
        "visualizationType": "3d-stack",
        "renderMode": "3d",
        "layout": "vertical",
        "animationStyle": "grow",
        "colorScheme": "categorical",
        "elementShape": "card",
        "showPointers": False,
        "showCallStack": True,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Vertical stack visualization for push/pop operations",
    },
    "queue": {
        "visualizationType": "2d-array",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "slide",
        "colorScheme": "status",
        "elementShape": "rectangle",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Horizontal queue visualization for enqueue/dequeue",
    },
    "linked-list": {
        "visualizationType": "2d-linkedlist",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "slide",
        "colorScheme": "status",
        "elementShape": "node",
        "showPointers": True,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Linked list node visualization with pointer connections",
    },
    "heap": {
        "visualizationType": "3d-heap",
        "renderMode": "3d",
        "layout": "hierarchical",
        "animationStyle": "swap",
        "colorScheme": "comparison",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Heap tree visualization for priority queue operations",
    },
    "trie": {
        "visualizationType": "3d-tree",
        "renderMode": "3d",
        "layout": "hierarchical",
        "animationStyle": "traverse",
        "colorScheme": "status",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Trie tree visualization for prefix-based lookups",
    },
    "matrix": {
        "visualizationType": "2d-grid",
        "renderMode": "2d",
        "layout": "grid",
        "animationStyle": "fill",
        "colorScheme": "heatmap",
        "elementShape": "rectangle",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": True,
        "reasoning": "Grid visualization for matrix traversal and operations",
    },
    "union-find": {
        "visualizationType": "3d-graph",
        "renderMode": "3d",
        "layout": "force-directed",
        "animationStyle": "traverse",
        "colorScheme": "categorical",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Graph visualization for union-find disjoint set operations",
    },
    "bit-manipulation": {
        "visualizationType": "2d-array",
        "renderMode": "2d",
        "layout": "horizontal",
        "animationStyle": "highlight",
        "colorScheme": "gradient",
        "elementShape": "rectangle",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Binary representation visualization for bit operations",
    },
    "pathfinding": {
        "visualizationType": "3d-graph",
        "renderMode": "3d",
        "layout": "force-directed",
        "animationStyle": "traverse",
        "colorScheme": "gradient",
        "elementShape": "node",
        "showPointers": False,
        "showCallStack": False,
        "showDPTable": False,
        "showMatrix": False,
        "reasoning": "Graph visualization for shortest path algorithms",
    },
}


def resolve_visualization(algorithm_type: str) -> dict:
    """
    Deterministically resolve visualization config from algorithm type.
    Zero API cost — pure lookup table.

    Args:
        algorithm_type: The algorithmType string from code analysis

    Returns:
        dict with visualizationType, renderMode, layout, etc.
    """
    config = VIZ_CONFIG_MAP.get(algorithm_type.lower(), _DEFAULT_VIZ)
    return {**config}  # Return a copy to prevent mutation
